// <auto-generated />
using System;
using A_Mover_Desktop_Final.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace A_Mover_Desktop_Final.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250920145218_updatemodelCHecklist")]
    partial class updatemodelCHecklist
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.Checklist", b =>
                {
                    b.Property<int>("IDChecklist")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDChecklist"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IDModeloMota")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("bit");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IDChecklist");

                    b.HasIndex("IDModeloMota");

                    b.ToTable("Checklist");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.ChecklistControlo", b =>
                {
                    b.Property<int>("IDChecklistControlo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDChecklistControlo"));

                    b.Property<int>("ControloFinal")
                        .HasColumnType("int");

                    b.Property<int>("IDChecklist")
                        .HasColumnType("int");

                    b.Property<int>("IDOrdemProducao")
                        .HasColumnType("int");

                    b.HasKey("IDChecklistControlo");

                    b.HasIndex("IDChecklist");

                    b.HasIndex("IDOrdemProducao");

                    b.ToTable("ChecklistControlo");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.ChecklistEmbalagem", b =>
                {
                    b.Property<int>("IDChecklistEmbalagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDChecklistEmbalagem"));

                    b.Property<int>("IDChecklist")
                        .HasColumnType("int");

                    b.Property<int>("IDOrdemProducao")
                        .HasColumnType("int");

                    b.Property<int>("Incluido")
                        .HasColumnType("int");

                    b.HasKey("IDChecklistEmbalagem");

                    b.HasIndex("IDChecklist");

                    b.HasIndex("IDOrdemProducao");

                    b.ToTable("ChecklistEmbalagem");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.ChecklistMontagem", b =>
                {
                    b.Property<int>("IDChecklistMontagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDChecklistMontagem"));

                    b.Property<int>("IDChecklist")
                        .HasColumnType("int");

                    b.Property<int>("IDOrdemProducao")
                        .HasColumnType("int");

                    b.Property<int>("Verificado")
                        .HasColumnType("int");

                    b.HasKey("IDChecklistMontagem");

                    b.HasIndex("IDChecklist");

                    b.HasIndex("IDOrdemProducao");

                    b.ToTable("ChecklistMontagem");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.Cliente", b =>
                {
                    b.Property<int>("IDCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCliente"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataModificacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaEncomenda")
                        .HasColumnType("datetime2");

                    b.HasKey("IDCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.Documento", b =>
                {
                    b.Property<int>("IDDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDDocumento"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDDocumento");

                    b.ToTable("Documento");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.DocumentosModelo", b =>
                {
                    b.Property<int>("IDDocumentosModelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDDocumentosModelo"));

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDDocumento")
                        .HasColumnType("int");

                    b.Property<int>("IDModelo")
                        .HasColumnType("int");

                    b.HasKey("IDDocumentosModelo");

                    b.HasIndex("IDModelo");

                    b.ToTable("DocumentosModelo");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.Encomenda", b =>
                {
                    b.Property<int>("IDEncomenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDEncomenda"));

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("IDCliente")
                        .HasColumnType("int");

                    b.Property<int>("IDModelo")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("IDEncomenda");

                    b.HasIndex("IDCliente");

                    b.HasIndex("IDModelo");

                    b.ToTable("Encomendas");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.ModeloMota", b =>
                {
                    b.Property<int>("IDModelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDModelo"));

                    b.Property<string>("CodigoProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataDescontinuacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicioProducao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDModelo");

                    b.ToTable("ModelosMota");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.ModeloPecasFixas", b =>
                {
                    b.Property<int>("IDMPF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDMPF"));

                    b.Property<int>("IDModelo")
                        .HasColumnType("int");

                    b.Property<int>("IDPeca")
                        .HasColumnType("int");

                    b.HasKey("IDMPF");

                    b.HasIndex("IDModelo");

                    b.HasIndex("IDPeca");

                    b.ToTable("ModeloPecasFixas");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.ModeloPecasSN", b =>
                {
                    b.Property<int>("IDModeloPSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDModeloPSN"));

                    b.Property<int>("IDModelo")
                        .HasColumnType("int");

                    b.Property<int>("IDPeca")
                        .HasColumnType("int");

                    b.Property<int?>("ModeloMotaIDModelo")
                        .HasColumnType("int");

                    b.HasKey("IDModeloPSN");

                    b.HasIndex("IDModelo");

                    b.HasIndex("IDPeca");

                    b.HasIndex("ModeloMotaIDModelo");

                    b.ToTable("ModeloPecasSN");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.Mota", b =>
                {
                    b.Property<int>("IDMota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDMota"));

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("IDModelo")
                        .HasColumnType("int");

                    b.Property<int>("IDOrdemProducao")
                        .HasColumnType("int");

                    b.Property<string>("NumeroIdentificacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quilometragem")
                        .HasColumnType("float");

                    b.HasKey("IDMota");

                    b.HasIndex("IDModelo");

                    b.HasIndex("IDOrdemProducao")
                        .IsUnique();

                    b.ToTable("Motas");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.MotasPecasSN", b =>
                {
                    b.Property<int>("IDMotasPecasSN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDMotasPecasSN"));

                    b.Property<int>("IDMota")
                        .HasColumnType("int");

                    b.Property<int>("IDPeca")
                        .HasColumnType("int");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDMotasPecasSN");

                    b.HasIndex("IDMota");

                    b.HasIndex("IDPeca");

                    b.ToTable("MotasPecasSN");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.OrdemProducao", b =>
                {
                    b.Property<int>("IDOrdemProducao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDOrdemProducao"));

                    b.Property<int?>("ClienteIDCliente")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EncomendaIDEncomenda")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("IDEncomenda")
                        .HasColumnType("int");

                    b.Property<int?>("ModeloMotaIDModelo")
                        .HasColumnType("int");

                    b.Property<string>("NumeroOrdem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDOrdemProducao");

                    b.HasIndex("ClienteIDCliente");

                    b.HasIndex("EncomendaIDEncomenda");

                    b.HasIndex("IDEncomenda");

                    b.HasIndex("ModeloMotaIDModelo");

                    b.ToTable("OrdemProducao");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.Pecas", b =>
                {
                    b.Property<int>("IDPeca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDPeca"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDPeca");

                    b.ToTable("Pecas");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.Servico", b =>
                {
                    b.Property<int>("IDServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDServico"));

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataServico")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("IDMota")
                        .HasColumnType("int");

                    b.Property<string>("NotasServico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IDServico");

                    b.HasIndex("IDMota");

                    b.ToTable("Servico");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.ServicosPecasAlteradas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("IDMotasPecasSN")
                        .HasColumnType("int");

                    b.Property<int>("IDServico")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("IDMotasPecasSN");

                    b.HasIndex("IDServico");

                    b.ToTable("ServicosPecasAlteradas");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.Utilizador", b =>
                {
                    b.Property<int>("IdUtilizador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilizador"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUtilizador");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.UtilizadorMota", b =>
                {
                    b.Property<int>("IDUtilizadorMota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUtilizadorMota"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("IDMota")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilizador")
                        .HasColumnType("int");

                    b.Property<string>("MotivoInativacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDUtilizadorMota");

                    b.HasIndex("IDMota");

                    b.HasIndex("IdUtilizador");

                    b.ToTable("UtilizadorMota");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.Checklist", b =>
                {
                    b.HasOne("A_Mover_Desktop_Final.Models.ModeloMota", "ModeloMota")
                        .WithMany()
                        .HasForeignKey("IDModeloMota");

                    b.Navigation("ModeloMota");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.ChecklistControlo", b =>
                {
                    b.HasOne("A_Mover_Desktop_Final.Models.Checklist", "Checklist")
                        .WithMany()
                        .HasForeignKey("IDChecklist")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_Mover_Desktop_Final.Models.OrdemProducao", "OrdemProducao")
                        .WithMany("ChecklistControlo")
                        .HasForeignKey("IDOrdemProducao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checklist");

                    b.Navigation("OrdemProducao");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.ChecklistEmbalagem", b =>
                {
                    b.HasOne("A_Mover_Desktop_Final.Models.Checklist", "Checklist")
                        .WithMany()
                        .HasForeignKey("IDChecklist")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_Mover_Desktop_Final.Models.OrdemProducao", "OrdemProducao")
                        .WithMany("ChecklistEmbalagem")
                        .HasForeignKey("IDOrdemProducao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checklist");

                    b.Navigation("OrdemProducao");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.ChecklistMontagem", b =>
                {
                    b.HasOne("A_Mover_Desktop_Final.Models.Checklist", "Checklist")
                        .WithMany()
                        .HasForeignKey("IDChecklist")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_Mover_Desktop_Final.Models.OrdemProducao", "OrdemProducao")
                        .WithMany("ChecklistMontagem")
                        .HasForeignKey("IDOrdemProducao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checklist");

                    b.Navigation("OrdemProducao");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.DocumentosModelo", b =>
                {
                    b.HasOne("A_Mover_Desktop_Final.Models.Documento", "Documento")
                        .WithMany()
                        .HasForeignKey("IDModelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_Mover_Desktop_Final.Models.ModeloMota", "ModeloMota")
                        .WithMany()
                        .HasForeignKey("IDModelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");

                    b.Navigation("ModeloMota");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.Encomenda", b =>
                {
                    b.HasOne("A_Mover_Desktop_Final.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IDCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_Mover_Desktop_Final.Models.ModeloMota", "ModeloMota")
                        .WithMany()
                        .HasForeignKey("IDModelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("ModeloMota");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.ModeloPecasFixas", b =>
                {
                    b.HasOne("A_Mover_Desktop_Final.Models.ModeloMota", "ModeloMota")
                        .WithMany("PecasFixas")
                        .HasForeignKey("IDModelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_Mover_Desktop_Final.Models.Pecas", "Pecas")
                        .WithMany()
                        .HasForeignKey("IDPeca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModeloMota");

                    b.Navigation("Pecas");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.ModeloPecasSN", b =>
                {
                    b.HasOne("A_Mover_Desktop_Final.Models.ModeloMota", "ModeloMota")
                        .WithMany()
                        .HasForeignKey("IDModelo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_Mover_Desktop_Final.Models.Pecas", "Pecas")
                        .WithMany()
                        .HasForeignKey("IDPeca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_Mover_Desktop_Final.Models.ModeloMota", null)
                        .WithMany("PecasSN")
                        .HasForeignKey("ModeloMotaIDModelo");

                    b.Navigation("ModeloMota");

                    b.Navigation("Pecas");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.Mota", b =>
                {
                    b.HasOne("A_Mover_Desktop_Final.Models.ModeloMota", "ModeloMota")
                        .WithMany()
                        .HasForeignKey("IDModelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_Mover_Desktop_Final.Models.OrdemProducao", "OrdemProducao")
                        .WithOne("Mota")
                        .HasForeignKey("A_Mover_Desktop_Final.Models.Mota", "IDOrdemProducao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModeloMota");

                    b.Navigation("OrdemProducao");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.MotasPecasSN", b =>
                {
                    b.HasOne("A_Mover_Desktop_Final.Models.Mota", "Mota")
                        .WithMany("MotasPecasSN")
                        .HasForeignKey("IDMota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_Mover_Desktop_Final.Models.Pecas", "Pecas")
                        .WithMany()
                        .HasForeignKey("IDPeca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mota");

                    b.Navigation("Pecas");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.OrdemProducao", b =>
                {
                    b.HasOne("A_Mover_Desktop_Final.Models.Cliente", null)
                        .WithMany("OrdensProducao")
                        .HasForeignKey("ClienteIDCliente");

                    b.HasOne("A_Mover_Desktop_Final.Models.Encomenda", null)
                        .WithMany("OrdemProducao")
                        .HasForeignKey("EncomendaIDEncomenda");

                    b.HasOne("A_Mover_Desktop_Final.Models.Encomenda", "Encomenda")
                        .WithMany()
                        .HasForeignKey("IDEncomenda")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_Mover_Desktop_Final.Models.ModeloMota", null)
                        .WithMany("OrdensProducao")
                        .HasForeignKey("ModeloMotaIDModelo");

                    b.Navigation("Encomenda");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.Servico", b =>
                {
                    b.HasOne("A_Mover_Desktop_Final.Models.Mota", "Mota")
                        .WithMany()
                        .HasForeignKey("IDMota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mota");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.ServicosPecasAlteradas", b =>
                {
                    b.HasOne("A_Mover_Desktop_Final.Models.MotasPecasSN", "MotasPecasSN")
                        .WithMany()
                        .HasForeignKey("IDMotasPecasSN")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("A_Mover_Desktop_Final.Models.Servico", "Servico")
                        .WithMany("PecasAlteradas")
                        .HasForeignKey("IDServico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MotasPecasSN");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.UtilizadorMota", b =>
                {
                    b.HasOne("A_Mover_Desktop_Final.Models.Mota", "Mota")
                        .WithMany()
                        .HasForeignKey("IDMota")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_Mover_Desktop_Final.Models.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("IdUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mota");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.Cliente", b =>
                {
                    b.Navigation("OrdensProducao");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.Encomenda", b =>
                {
                    b.Navigation("OrdemProducao");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.ModeloMota", b =>
                {
                    b.Navigation("OrdensProducao");

                    b.Navigation("PecasFixas");

                    b.Navigation("PecasSN");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.Mota", b =>
                {
                    b.Navigation("MotasPecasSN");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.OrdemProducao", b =>
                {
                    b.Navigation("ChecklistControlo");

                    b.Navigation("ChecklistEmbalagem");

                    b.Navigation("ChecklistMontagem");

                    b.Navigation("Mota");
                });

            modelBuilder.Entity("A_Mover_Desktop_Final.Models.Servico", b =>
                {
                    b.Navigation("PecasAlteradas");
                });
#pragma warning restore 612, 618
        }
    }
}
