name: Deploy na VPS Amen (A-MoVer)

on:
  push:
    branches:
      - main  # O deploy acontece sempre que houver um push para a main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Executar comandos na VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /root/CicloVidaMota
            
            # 1. Se a pasta .git não existir, clonamos o repo
            if [ ! -d ".git" ]; then
              git clone https://github.com/A-MoVer/AMoverDesktopFinal.git .
            fi
            
            # 2. Atualizar o código na VPS
            git pull origin main
            
            # 3. Reconstruir a imagem Docker e reiniciar os contentores
            # O --build garante que a "alteração da letra" seja compilada
            docker-compose up -d --build
